sonar.projectKey=webuddhist_worker
sonar.organization=webuddhist
sonar.host.url=https://sonarcloud.io

sonar.sources=worker_api
sonar.tests=tests
sonar.python.version=3.12
sonar.python.coverage.reportPaths=coverage.xml
